### ISSUE TITLE
Errors when negotiating with .net core signalr 1.0.4

### ISSUE THREAD

**Issue by finsterdexter** [carterjones/signalr#12]
Expected behavior: This signalr library, when specifying protocol 1.5, should perform an OPTIONS request against the negotiate endpoint, and on a 204, then perform a POST request (or GET if using protocol 1.4). Also, if I set the client scheme to "ws" or "wss" the negotiate calls should still be "http" or "https", not "ws" or "wss".

Actual behavior: Regardless of protocol or scheme, the negotiate endpoint is hit with a GET request using the passed in scheme. So, if I want to hit `ws://localhost:8080/info` the Negotiate url will be `ws://localhost:8080/info/negotiate?clientProtocol=1.4&connectionData=whatever`

Instead, the negotiate URL should be `http://localhost:8080/info/negotiate?clientProtocol=1.4&connectionData=whatever` and should be a POST if protocol is 1.5, otherwise I get `405 method not allowed`.

Although, maybe I'm barking up the wrong tree, and this library was never meant to connect to .net core signalr?

**Comment by carterjones** [comment]
Thanks for the bug report! I appreciate all the detail. Regarding your final point, you are correct: this library was never meant to connect to .net core signalr. However, I am certainly open to folks contributing and improving this library :) I think this would be an excellent addition.

I'll leave this open so that folks can contribute or if I'm able to set aside some time, I might be able to implement this as well.

One thing that would be very useful would be a sample server. Do you happen to know of a sample server that could be used that would expect and be able to handle the type of client side behavior you are describing?

**Comment by finsterdexter** [comment]
I don't know of a good sample, off the top of my head. I did find the current specs for the .NET core SignalR:

https://github.com/aspnet/SignalR/tree/master/specs
